import {createContext,useContext,useMemo} from "react";
import {defaultProfile} from "../data/profile";
import {useLocalStorage} from "../hooks/useLocalStorage";
const AppContext=createContext(null);
const defaultResume={fileName:"",rawText:"",summary:"Computer science graduate student focused on software engineering, product development, and practical AI-enabled systems.",skills:["React","TypeScript","JavaScript","Python","SQL","AWS","Docker","REST APIs"],experience:"Built React and TypeScript interfaces, Python services, SQL-backed applications, AWS deployments, Docker workflows, and software engineering projects."};
const defaultAnswers={whyInterested:"I’m interested in this role because it combines hands-on software engineering with a product environment where I can contribute quickly and keep learning.",workAuthorization:"Yes"};
export function AppProvider({children}){const [profile,setProfile]=useLocalStorage("getajob.profile",defaultProfile);const [resume,setResume]=useLocalStorage("getajob.resume",defaultResume);const [savedJobs,setSavedJobs]=useLocalStorage("getajob.saved",[]);const [hiddenJobs,setHiddenJobs]=useLocalStorage("getajob.hidden",[]);const [applications,setApplications]=useLocalStorage("getajob.applications",{});const [applicationDrafts,setApplicationDrafts]=useLocalStorage("getajob.drafts",{});const [reusableAnswers,setReusableAnswers]=useLocalStorage("getajob.answers",defaultAnswers);const [interviewHistory,setInterviewHistory]=useLocalStorage("getajob.interviewHistory",[]);const savedSet=useMemo(()=>new Set(savedJobs),[savedJobs]);const hiddenSet=useMemo(()=>new Set(hiddenJobs),[hiddenJobs]);
function toggleSaved(id){setSavedJobs(c=>c.includes(id)?c.filter(x=>x!==id):[...c,id])}function toggleHidden(id){setHiddenJobs(c=>c.includes(id)?c.filter(x=>x!==id):[...c,id])}function upsertApplication(id,status="Interested",extra={}){setApplications(c=>({...c,[id]:{...(c[id]||{}),status,updatedAt:new Date().toISOString(),...extra}}))}function removeApplication(id){setApplications(c=>{const n={...c};delete n[id];return n})}function saveDraft(id,draft){setApplicationDrafts(c=>({...c,[id]:{...draft,savedAt:new Date().toISOString()}}))}function clearDraft(id){setApplicationDrafts(c=>{const n={...c};delete n[id];return n})}
return <AppContext.Provider value={{profile,setProfile,resume,setResume,savedJobs,savedSet,toggleSaved,hiddenJobs,hiddenSet,toggleHidden,applications,setApplications,upsertApplication,removeApplication,applicationDrafts,saveDraft,clearDraft,reusableAnswers,setReusableAnswers,interviewHistory,setInterviewHistory}}>{children}</AppContext.Provider>}
export function useApp(){const v=useContext(AppContext);if(!v)throw new Error("useApp must be used inside AppProvider");return v}
